spring:
#  main:
#    allow-bean-definition-overriding: true
  jms:
    pub-sub-domain: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: demo-service
      auto-offset-reset: earliest
#    streams:
#      application-id: stream-application

#logging:
#  level:
#    root: DEBUG
#    org.springframework.web: ERROR
#    com.memorynotfound: DEBUG